<?php
/**
 * MembershipOrderItemsApi
 * PHP version 5
 *
 * @category Class
 * @package  FomF\Ungerboeck\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ungerboeck API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FomF\Ungerboeck\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use FomF\Ungerboeck\Client\ApiException;
use FomF\Ungerboeck\Client\Configuration;
use FomF\Ungerboeck\Client\HeaderSelector;
use FomF\Ungerboeck\Client\ObjectSerializer;

/**
 * MembershipOrderItemsApi Class Doc Comment
 *
 * @category Class
 * @package  FomF\Ungerboeck\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class MembershipOrderItemsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation membershipOrderItemsDeleteMembershipOrderItem
     *
     * Delete a order item from an order
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return void
     */
    public function membershipOrderItemsDeleteMembershipOrderItem($org_code, $order_number, $order_line_number)
    {
        $this->membershipOrderItemsDeleteMembershipOrderItemWithHttpInfo($org_code, $order_number, $order_line_number);
    }

    /**
     * Operation membershipOrderItemsDeleteMembershipOrderItemWithHttpInfo
     *
     * Delete a order item from an order
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of null, HTTP status code, HTTP response headers (array of strings)
     */
    public function membershipOrderItemsDeleteMembershipOrderItemWithHttpInfo($org_code, $order_number, $order_line_number)
    {
        $returnType = '';
        $request = $this->membershipOrderItemsDeleteMembershipOrderItemRequest($org_code, $order_number, $order_line_number);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            return [null, $statusCode, $response->getHeaders()];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
            }
            throw $e;
        }
    }

    /**
     * Operation membershipOrderItemsDeleteMembershipOrderItemAsync
     *
     * Delete a order item from an order
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsDeleteMembershipOrderItemAsync($org_code, $order_number, $order_line_number)
    {
        return $this->membershipOrderItemsDeleteMembershipOrderItemAsyncWithHttpInfo($org_code, $order_number, $order_line_number)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation membershipOrderItemsDeleteMembershipOrderItemAsyncWithHttpInfo
     *
     * Delete a order item from an order
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsDeleteMembershipOrderItemAsyncWithHttpInfo($org_code, $order_number, $order_line_number)
    {
        $returnType = '';
        $request = $this->membershipOrderItemsDeleteMembershipOrderItemRequest($org_code, $order_number, $order_line_number);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    return [null, $response->getStatusCode(), $response->getHeaders()];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'membershipOrderItemsDeleteMembershipOrderItem'
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function membershipOrderItemsDeleteMembershipOrderItemRequest($org_code, $order_number, $order_line_number)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling membershipOrderItemsDeleteMembershipOrderItem'
            );
        }
        // verify the required parameter 'order_number' is set
        if ($order_number === null || (is_array($order_number) && count($order_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_number when calling membershipOrderItemsDeleteMembershipOrderItem'
            );
        }
        // verify the required parameter 'order_line_number' is set
        if ($order_line_number === null || (is_array($order_line_number) && count($order_line_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_line_number when calling membershipOrderItemsDeleteMembershipOrderItem'
            );
        }

        $resourcePath = '/api/v1/MembershipOrderItems/{OrgCode}/{OrderNumber}/{OrderLineNumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }
        // path params
        if ($order_number !== null) {
            $resourcePath = str_replace(
                '{' . 'OrderNumber' . '}',
                ObjectSerializer::toPathValue($order_number),
                $resourcePath
            );
        }
        // path params
        if ($order_line_number !== null) {
            $resourcePath = str_replace(
                '{' . 'OrderLineNumber' . '}',
                ObjectSerializer::toPathValue($order_line_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                []
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                [],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'DELETE',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation membershipOrderItemsGetMembershipOrderItem
     *
     * Get a membership order item by its parameters
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel
     */
    public function membershipOrderItemsGetMembershipOrderItem($org_code, $order_number, $order_line_number)
    {
        list($response) = $this->membershipOrderItemsGetMembershipOrderItemWithHttpInfo($org_code, $order_number, $order_line_number);
        return $response;
    }

    /**
     * Operation membershipOrderItemsGetMembershipOrderItemWithHttpInfo
     *
     * Get a membership order item by its parameters
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function membershipOrderItemsGetMembershipOrderItemWithHttpInfo($org_code, $order_number, $order_line_number)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel';
        $request = $this->membershipOrderItemsGetMembershipOrderItemRequest($org_code, $order_number, $order_line_number);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation membershipOrderItemsGetMembershipOrderItemAsync
     *
     * Get a membership order item by its parameters
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsGetMembershipOrderItemAsync($org_code, $order_number, $order_line_number)
    {
        return $this->membershipOrderItemsGetMembershipOrderItemAsyncWithHttpInfo($org_code, $order_number, $order_line_number)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation membershipOrderItemsGetMembershipOrderItemAsyncWithHttpInfo
     *
     * Get a membership order item by its parameters
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsGetMembershipOrderItemAsyncWithHttpInfo($org_code, $order_number, $order_line_number)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel';
        $request = $this->membershipOrderItemsGetMembershipOrderItemRequest($org_code, $order_number, $order_line_number);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'membershipOrderItemsGetMembershipOrderItem'
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The Order Number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function membershipOrderItemsGetMembershipOrderItemRequest($org_code, $order_number, $order_line_number)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling membershipOrderItemsGetMembershipOrderItem'
            );
        }
        // verify the required parameter 'order_number' is set
        if ($order_number === null || (is_array($order_number) && count($order_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_number when calling membershipOrderItemsGetMembershipOrderItem'
            );
        }
        // verify the required parameter 'order_line_number' is set
        if ($order_line_number === null || (is_array($order_line_number) && count($order_line_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_line_number when calling membershipOrderItemsGetMembershipOrderItem'
            );
        }

        $resourcePath = '/api/v1/MembershipOrderItems/{OrgCode}/{OrderNumber}/{OrderLineNumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }
        // path params
        if ($order_number !== null) {
            $resourcePath = str_replace(
                '{' . 'OrderNumber' . '}',
                ObjectSerializer::toPathValue($order_number),
                $resourcePath
            );
        }
        // path params
        if ($order_line_number !== null) {
            $resourcePath = str_replace(
                '{' . 'OrderLineNumber' . '}',
                ObjectSerializer::toPathValue($order_line_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation membershipOrderItemsGetMembershipOrderItemsList
     *
     * Search for membership order items using OData.
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search Search string using OData with model properties for the filter, Page and Page_Size to navigate (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel[]
     */
    public function membershipOrderItemsGetMembershipOrderItemsList($org_code, $search)
    {
        list($response) = $this->membershipOrderItemsGetMembershipOrderItemsListWithHttpInfo($org_code, $search);
        return $response;
    }

    /**
     * Operation membershipOrderItemsGetMembershipOrderItemsListWithHttpInfo
     *
     * Search for membership order items using OData.
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search Search string using OData with model properties for the filter, Page and Page_Size to navigate (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel[], HTTP status code, HTTP response headers (array of strings)
     */
    public function membershipOrderItemsGetMembershipOrderItemsListWithHttpInfo($org_code, $search)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel[]';
        $request = $this->membershipOrderItemsGetMembershipOrderItemsListRequest($org_code, $search);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel[]',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation membershipOrderItemsGetMembershipOrderItemsListAsync
     *
     * Search for membership order items using OData.
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search Search string using OData with model properties for the filter, Page and Page_Size to navigate (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsGetMembershipOrderItemsListAsync($org_code, $search)
    {
        return $this->membershipOrderItemsGetMembershipOrderItemsListAsyncWithHttpInfo($org_code, $search)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation membershipOrderItemsGetMembershipOrderItemsListAsyncWithHttpInfo
     *
     * Search for membership order items using OData.
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search Search string using OData with model properties for the filter, Page and Page_Size to navigate (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsGetMembershipOrderItemsListAsyncWithHttpInfo($org_code, $search)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel[]';
        $request = $this->membershipOrderItemsGetMembershipOrderItemsListRequest($org_code, $search);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'membershipOrderItemsGetMembershipOrderItemsList'
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search Search string using OData with model properties for the filter, Page and Page_Size to navigate (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function membershipOrderItemsGetMembershipOrderItemsListRequest($org_code, $search)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling membershipOrderItemsGetMembershipOrderItemsList'
            );
        }
        // verify the required parameter 'search' is set
        if ($search === null || (is_array($search) && count($search) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $search when calling membershipOrderItemsGetMembershipOrderItemsList'
            );
        }

        $resourcePath = '/api/v1/MembershipOrderItems/{OrgCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search);
        }

        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation membershipOrderItemsPostMembershipOrderItem
     *
     * Add an item to an existing membership order
     *
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to add. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel
     */
    public function membershipOrderItemsPostMembershipOrderItem($data)
    {
        list($response) = $this->membershipOrderItemsPostMembershipOrderItemWithHttpInfo($data);
        return $response;
    }

    /**
     * Operation membershipOrderItemsPostMembershipOrderItemWithHttpInfo
     *
     * Add an item to an existing membership order
     *
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to add. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function membershipOrderItemsPostMembershipOrderItemWithHttpInfo($data)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel';
        $request = $this->membershipOrderItemsPostMembershipOrderItemRequest($data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation membershipOrderItemsPostMembershipOrderItemAsync
     *
     * Add an item to an existing membership order
     *
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to add. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsPostMembershipOrderItemAsync($data)
    {
        return $this->membershipOrderItemsPostMembershipOrderItemAsyncWithHttpInfo($data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation membershipOrderItemsPostMembershipOrderItemAsyncWithHttpInfo
     *
     * Add an item to an existing membership order
     *
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to add. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsPostMembershipOrderItemAsyncWithHttpInfo($data)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel';
        $request = $this->membershipOrderItemsPostMembershipOrderItemRequest($data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'membershipOrderItemsPostMembershipOrderItem'
     *
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to add. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function membershipOrderItemsPostMembershipOrderItemRequest($data)
    {
        // verify the required parameter 'data' is set
        if ($data === null || (is_array($data) && count($data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data when calling membershipOrderItemsPostMembershipOrderItem'
            );
        }

        $resourcePath = '/api/v1/MembershipOrderItems';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($data)) {
            $_tempBody = $data;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation membershipOrderItemsPutMembershipOrderItem
     *
     * Edit a item on a membership order
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The order number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to edit. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel
     */
    public function membershipOrderItemsPutMembershipOrderItem($org_code, $order_number, $order_line_number, $data)
    {
        list($response) = $this->membershipOrderItemsPutMembershipOrderItemWithHttpInfo($org_code, $order_number, $order_line_number, $data);
        return $response;
    }

    /**
     * Operation membershipOrderItemsPutMembershipOrderItemWithHttpInfo
     *
     * Edit a item on a membership order
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The order number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to edit. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function membershipOrderItemsPutMembershipOrderItemWithHttpInfo($org_code, $order_number, $order_line_number, $data)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel';
        $request = $this->membershipOrderItemsPutMembershipOrderItemRequest($org_code, $order_number, $order_line_number, $data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation membershipOrderItemsPutMembershipOrderItemAsync
     *
     * Edit a item on a membership order
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The order number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to edit. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsPutMembershipOrderItemAsync($org_code, $order_number, $order_line_number, $data)
    {
        return $this->membershipOrderItemsPutMembershipOrderItemAsyncWithHttpInfo($org_code, $order_number, $order_line_number, $data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation membershipOrderItemsPutMembershipOrderItemAsyncWithHttpInfo
     *
     * Edit a item on a membership order
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The order number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to edit. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function membershipOrderItemsPutMembershipOrderItemAsyncWithHttpInfo($org_code, $order_number, $order_line_number, $data)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel';
        $request = $this->membershipOrderItemsPutMembershipOrderItemRequest($org_code, $order_number, $order_line_number, $data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'membershipOrderItemsPutMembershipOrderItem'
     *
     * @param  string $org_code The organization code of the membership order item. (required)
     * @param  int $order_number The order number of the membership order item&#39;s parent order. (required)
     * @param  int $order_line_number The Order Item Number of the membership order item. (required)
     * @param  \FomF\Ungerboeck\Client\Model\MembershipOrderItemsModel $data (Include in the HTTP Body) A MembershipOrderItemsModel entry to edit. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function membershipOrderItemsPutMembershipOrderItemRequest($org_code, $order_number, $order_line_number, $data)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling membershipOrderItemsPutMembershipOrderItem'
            );
        }
        // verify the required parameter 'order_number' is set
        if ($order_number === null || (is_array($order_number) && count($order_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_number when calling membershipOrderItemsPutMembershipOrderItem'
            );
        }
        // verify the required parameter 'order_line_number' is set
        if ($order_line_number === null || (is_array($order_line_number) && count($order_line_number) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $order_line_number when calling membershipOrderItemsPutMembershipOrderItem'
            );
        }
        // verify the required parameter 'data' is set
        if ($data === null || (is_array($data) && count($data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data when calling membershipOrderItemsPutMembershipOrderItem'
            );
        }

        $resourcePath = '/api/v1/MembershipOrderItems/{OrgCode}/{OrderNumber}/{OrderLineNumber}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }
        // path params
        if ($order_number !== null) {
            $resourcePath = str_replace(
                '{' . 'OrderNumber' . '}',
                ObjectSerializer::toPathValue($order_number),
                $resourcePath
            );
        }
        // path params
        if ($order_line_number !== null) {
            $resourcePath = str_replace(
                '{' . 'OrderLineNumber' . '}',
                ObjectSerializer::toPathValue($order_line_number),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($data)) {
            $_tempBody = $data;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
