<?php
/**
 * OrderRegistrantsApi
 * PHP version 5
 *
 * @category Class
 * @package  FomF\Ungerboeck\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ungerboeck API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace FomF\Ungerboeck\Client\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use FomF\Ungerboeck\Client\ApiException;
use FomF\Ungerboeck\Client\Configuration;
use FomF\Ungerboeck\Client\HeaderSelector;
use FomF\Ungerboeck\Client\ObjectSerializer;

/**
 * OrderRegistrantsApi Class Doc Comment
 *
 * @category Class
 * @package  FomF\Ungerboeck\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OrderRegistrantsApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation orderRegistrantsCheckIn
     *
     * Extended (Registration Orders) - Registrant check-in
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is checking in to. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function orderRegistrantsCheckIn($org_code, $registrant_sequence_nbr, $event_id)
    {
        list($response) = $this->orderRegistrantsCheckInWithHttpInfo($org_code, $registrant_sequence_nbr, $event_id);
        return $response;
    }

    /**
     * Operation orderRegistrantsCheckInWithHttpInfo
     *
     * Extended (Registration Orders) - Registrant check-in
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is checking in to. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderRegistrantsCheckInWithHttpInfo($org_code, $registrant_sequence_nbr, $event_id)
    {
        $returnType = 'object';
        $request = $this->orderRegistrantsCheckInRequest($org_code, $registrant_sequence_nbr, $event_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation orderRegistrantsCheckInAsync
     *
     * Extended (Registration Orders) - Registrant check-in
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is checking in to. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsCheckInAsync($org_code, $registrant_sequence_nbr, $event_id)
    {
        return $this->orderRegistrantsCheckInAsyncWithHttpInfo($org_code, $registrant_sequence_nbr, $event_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderRegistrantsCheckInAsyncWithHttpInfo
     *
     * Extended (Registration Orders) - Registrant check-in
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is checking in to. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsCheckInAsyncWithHttpInfo($org_code, $registrant_sequence_nbr, $event_id)
    {
        $returnType = 'object';
        $request = $this->orderRegistrantsCheckInRequest($org_code, $registrant_sequence_nbr, $event_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderRegistrantsCheckIn'
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is checking in to. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function orderRegistrantsCheckInRequest($org_code, $registrant_sequence_nbr, $event_id)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling orderRegistrantsCheckIn'
            );
        }
        // verify the required parameter 'registrant_sequence_nbr' is set
        if ($registrant_sequence_nbr === null || (is_array($registrant_sequence_nbr) && count($registrant_sequence_nbr) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $registrant_sequence_nbr when calling orderRegistrantsCheckIn'
            );
        }
        // verify the required parameter 'event_id' is set
        if ($event_id === null || (is_array($event_id) && count($event_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_id when calling orderRegistrantsCheckIn'
            );
        }

        $resourcePath = '/api/v1/OrderRegistrants/{OrgCode}/{RegistrantSequenceNbr}/{EventID}/CheckIn';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }
        // path params
        if ($registrant_sequence_nbr !== null) {
            $resourcePath = str_replace(
                '{' . 'RegistrantSequenceNbr' . '}',
                ObjectSerializer::toPathValue($registrant_sequence_nbr),
                $resourcePath
            );
        }
        // path params
        if ($event_id !== null) {
            $resourcePath = str_replace(
                '{' . 'EventID' . '}',
                ObjectSerializer::toPathValue($event_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderRegistrantsClearCheckIn
     *
     * Extended (Registration Orders) - Registrant clear check-in
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is clear checking in. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function orderRegistrantsClearCheckIn($org_code, $registrant_sequence_nbr, $event_id)
    {
        list($response) = $this->orderRegistrantsClearCheckInWithHttpInfo($org_code, $registrant_sequence_nbr, $event_id);
        return $response;
    }

    /**
     * Operation orderRegistrantsClearCheckInWithHttpInfo
     *
     * Extended (Registration Orders) - Registrant clear check-in
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is clear checking in. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderRegistrantsClearCheckInWithHttpInfo($org_code, $registrant_sequence_nbr, $event_id)
    {
        $returnType = 'object';
        $request = $this->orderRegistrantsClearCheckInRequest($org_code, $registrant_sequence_nbr, $event_id);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation orderRegistrantsClearCheckInAsync
     *
     * Extended (Registration Orders) - Registrant clear check-in
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is clear checking in. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsClearCheckInAsync($org_code, $registrant_sequence_nbr, $event_id)
    {
        return $this->orderRegistrantsClearCheckInAsyncWithHttpInfo($org_code, $registrant_sequence_nbr, $event_id)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderRegistrantsClearCheckInAsyncWithHttpInfo
     *
     * Extended (Registration Orders) - Registrant clear check-in
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is clear checking in. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsClearCheckInAsyncWithHttpInfo($org_code, $registrant_sequence_nbr, $event_id)
    {
        $returnType = 'object';
        $request = $this->orderRegistrantsClearCheckInRequest($org_code, $registrant_sequence_nbr, $event_id);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderRegistrantsClearCheckIn'
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  int $event_id Event ID of the event the registrant is clear checking in. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function orderRegistrantsClearCheckInRequest($org_code, $registrant_sequence_nbr, $event_id)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling orderRegistrantsClearCheckIn'
            );
        }
        // verify the required parameter 'registrant_sequence_nbr' is set
        if ($registrant_sequence_nbr === null || (is_array($registrant_sequence_nbr) && count($registrant_sequence_nbr) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $registrant_sequence_nbr when calling orderRegistrantsClearCheckIn'
            );
        }
        // verify the required parameter 'event_id' is set
        if ($event_id === null || (is_array($event_id) && count($event_id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $event_id when calling orderRegistrantsClearCheckIn'
            );
        }

        $resourcePath = '/api/v1/OrderRegistrants/{OrgCode}/{RegistrantSequenceNbr}/{EventID}/ClearCheckIn';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }
        // path params
        if ($registrant_sequence_nbr !== null) {
            $resourcePath = str_replace(
                '{' . 'RegistrantSequenceNbr' . '}',
                ObjectSerializer::toPathValue($registrant_sequence_nbr),
                $resourcePath
            );
        }
        // path params
        if ($event_id !== null) {
            $resourcePath = str_replace(
                '{' . 'EventID' . '}',
                ObjectSerializer::toPathValue($event_id),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderRegistrantsGetOrderRegistrant
     *
     * Standard - Get a single order registrant by its parameters
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel
     */
    public function orderRegistrantsGetOrderRegistrant($org_code, $registrant_sequence_nbr)
    {
        list($response) = $this->orderRegistrantsGetOrderRegistrantWithHttpInfo($org_code, $registrant_sequence_nbr);
        return $response;
    }

    /**
     * Operation orderRegistrantsGetOrderRegistrantWithHttpInfo
     *
     * Standard - Get a single order registrant by its parameters
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderRegistrantsGetOrderRegistrantWithHttpInfo($org_code, $registrant_sequence_nbr)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel';
        $request = $this->orderRegistrantsGetOrderRegistrantRequest($org_code, $registrant_sequence_nbr);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation orderRegistrantsGetOrderRegistrantAsync
     *
     * Standard - Get a single order registrant by its parameters
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsGetOrderRegistrantAsync($org_code, $registrant_sequence_nbr)
    {
        return $this->orderRegistrantsGetOrderRegistrantAsyncWithHttpInfo($org_code, $registrant_sequence_nbr)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderRegistrantsGetOrderRegistrantAsyncWithHttpInfo
     *
     * Standard - Get a single order registrant by its parameters
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsGetOrderRegistrantAsyncWithHttpInfo($org_code, $registrant_sequence_nbr)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel';
        $request = $this->orderRegistrantsGetOrderRegistrantRequest($org_code, $registrant_sequence_nbr);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderRegistrantsGetOrderRegistrant'
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function orderRegistrantsGetOrderRegistrantRequest($org_code, $registrant_sequence_nbr)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling orderRegistrantsGetOrderRegistrant'
            );
        }
        // verify the required parameter 'registrant_sequence_nbr' is set
        if ($registrant_sequence_nbr === null || (is_array($registrant_sequence_nbr) && count($registrant_sequence_nbr) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $registrant_sequence_nbr when calling orderRegistrantsGetOrderRegistrant'
            );
        }

        $resourcePath = '/api/v1/OrderRegistrants/{OrgCode}/{RegistrantSequenceNbr}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }
        // path params
        if ($registrant_sequence_nbr !== null) {
            $resourcePath = str_replace(
                '{' . 'RegistrantSequenceNbr' . '}',
                ObjectSerializer::toPathValue($registrant_sequence_nbr),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderRegistrantsGetOrderRegistrantList
     *
     * Standard - Search for order registrant using OData.  Note, this will not return user fields.  Use the single GET endpoint to retrieve user fields.
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search &lt;a href&#x3D;\&quot;https://supportcenter.ungerboeck.com/hc/en-us/articles/115010610608-Searching-Using-the-API\&quot;&gt;How to make an Ungerboeck API search&lt;/a&gt; (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel
     */
    public function orderRegistrantsGetOrderRegistrantList($org_code, $search)
    {
        list($response) = $this->orderRegistrantsGetOrderRegistrantListWithHttpInfo($org_code, $search);
        return $response;
    }

    /**
     * Operation orderRegistrantsGetOrderRegistrantListWithHttpInfo
     *
     * Standard - Search for order registrant using OData.  Note, this will not return user fields.  Use the single GET endpoint to retrieve user fields.
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search &lt;a href&#x3D;\&quot;https://supportcenter.ungerboeck.com/hc/en-us/articles/115010610608-Searching-Using-the-API\&quot;&gt;How to make an Ungerboeck API search&lt;/a&gt; (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderRegistrantsGetOrderRegistrantListWithHttpInfo($org_code, $search)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel';
        $request = $this->orderRegistrantsGetOrderRegistrantListRequest($org_code, $search);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation orderRegistrantsGetOrderRegistrantListAsync
     *
     * Standard - Search for order registrant using OData.  Note, this will not return user fields.  Use the single GET endpoint to retrieve user fields.
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search &lt;a href&#x3D;\&quot;https://supportcenter.ungerboeck.com/hc/en-us/articles/115010610608-Searching-Using-the-API\&quot;&gt;How to make an Ungerboeck API search&lt;/a&gt; (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsGetOrderRegistrantListAsync($org_code, $search)
    {
        return $this->orderRegistrantsGetOrderRegistrantListAsyncWithHttpInfo($org_code, $search)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderRegistrantsGetOrderRegistrantListAsyncWithHttpInfo
     *
     * Standard - Search for order registrant using OData.  Note, this will not return user fields.  Use the single GET endpoint to retrieve user fields.
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search &lt;a href&#x3D;\&quot;https://supportcenter.ungerboeck.com/hc/en-us/articles/115010610608-Searching-Using-the-API\&quot;&gt;How to make an Ungerboeck API search&lt;/a&gt; (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsGetOrderRegistrantListAsyncWithHttpInfo($org_code, $search)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel';
        $request = $this->orderRegistrantsGetOrderRegistrantListRequest($org_code, $search);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderRegistrantsGetOrderRegistrantList'
     *
     * @param  string $org_code The organization code in which the search will take place (required)
     * @param  string $search &lt;a href&#x3D;\&quot;https://supportcenter.ungerboeck.com/hc/en-us/articles/115010610608-Searching-Using-the-API\&quot;&gt;How to make an Ungerboeck API search&lt;/a&gt; (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function orderRegistrantsGetOrderRegistrantListRequest($org_code, $search)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling orderRegistrantsGetOrderRegistrantList'
            );
        }
        // verify the required parameter 'search' is set
        if ($search === null || (is_array($search) && count($search) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $search when calling orderRegistrantsGetOrderRegistrantList'
            );
        }

        $resourcePath = '/api/v1/OrderRegistrants/{OrgCode}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($search !== null) {
            $queryParams['search'] = ObjectSerializer::toQueryValue($search);
        }

        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderRegistrantsPutOrderRegistrant
     *
     * Standard - Edit a order registrant
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel $data (Include in the HTTP Body) An OrderRegistrantsModel entry to edit. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel
     */
    public function orderRegistrantsPutOrderRegistrant($org_code, $registrant_sequence_nbr, $data)
    {
        list($response) = $this->orderRegistrantsPutOrderRegistrantWithHttpInfo($org_code, $registrant_sequence_nbr, $data);
        return $response;
    }

    /**
     * Operation orderRegistrantsPutOrderRegistrantWithHttpInfo
     *
     * Standard - Edit a order registrant
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel $data (Include in the HTTP Body) An OrderRegistrantsModel entry to edit. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderRegistrantsPutOrderRegistrantWithHttpInfo($org_code, $registrant_sequence_nbr, $data)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel';
        $request = $this->orderRegistrantsPutOrderRegistrantRequest($org_code, $registrant_sequence_nbr, $data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation orderRegistrantsPutOrderRegistrantAsync
     *
     * Standard - Edit a order registrant
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel $data (Include in the HTTP Body) An OrderRegistrantsModel entry to edit. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsPutOrderRegistrantAsync($org_code, $registrant_sequence_nbr, $data)
    {
        return $this->orderRegistrantsPutOrderRegistrantAsyncWithHttpInfo($org_code, $registrant_sequence_nbr, $data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderRegistrantsPutOrderRegistrantAsyncWithHttpInfo
     *
     * Standard - Edit a order registrant
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel $data (Include in the HTTP Body) An OrderRegistrantsModel entry to edit. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsPutOrderRegistrantAsyncWithHttpInfo($org_code, $registrant_sequence_nbr, $data)
    {
        $returnType = '\FomF\Ungerboeck\Client\Model\OrderRegistrantsModel';
        $request = $this->orderRegistrantsPutOrderRegistrantRequest($org_code, $registrant_sequence_nbr, $data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderRegistrantsPutOrderRegistrant'
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\OrderRegistrantsModel $data (Include in the HTTP Body) An OrderRegistrantsModel entry to edit. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function orderRegistrantsPutOrderRegistrantRequest($org_code, $registrant_sequence_nbr, $data)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling orderRegistrantsPutOrderRegistrant'
            );
        }
        // verify the required parameter 'registrant_sequence_nbr' is set
        if ($registrant_sequence_nbr === null || (is_array($registrant_sequence_nbr) && count($registrant_sequence_nbr) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $registrant_sequence_nbr when calling orderRegistrantsPutOrderRegistrant'
            );
        }
        // verify the required parameter 'data' is set
        if ($data === null || (is_array($data) && count($data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data when calling orderRegistrantsPutOrderRegistrant'
            );
        }

        $resourcePath = '/api/v1/OrderRegistrants/{OrgCode}/{RegistrantSequenceNbr}';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }
        // path params
        if ($registrant_sequence_nbr !== null) {
            $resourcePath = str_replace(
                '{' . 'RegistrantSequenceNbr' . '}',
                ObjectSerializer::toPathValue($registrant_sequence_nbr),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($data)) {
            $_tempBody = $data;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation orderRegistrantsSetRegistrantApproval
     *
     * Extended (Registration Orders) - Set order registrant Approval Status
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\RegistrationApprovalsModel $data (Include in the HTTP Body) An RegistrationApprovalsModel entry to to change the approval status of a registrant. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return object
     */
    public function orderRegistrantsSetRegistrantApproval($org_code, $registrant_sequence_nbr, $data)
    {
        list($response) = $this->orderRegistrantsSetRegistrantApprovalWithHttpInfo($org_code, $registrant_sequence_nbr, $data);
        return $response;
    }

    /**
     * Operation orderRegistrantsSetRegistrantApprovalWithHttpInfo
     *
     * Extended (Registration Orders) - Set order registrant Approval Status
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\RegistrationApprovalsModel $data (Include in the HTTP Body) An RegistrationApprovalsModel entry to to change the approval status of a registrant. (required)
     *
     * @throws \FomF\Ungerboeck\Client\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of object, HTTP status code, HTTP response headers (array of strings)
     */
    public function orderRegistrantsSetRegistrantApprovalWithHttpInfo($org_code, $registrant_sequence_nbr, $data)
    {
        $returnType = 'object';
        $request = $this->orderRegistrantsSetRegistrantApprovalRequest($org_code, $registrant_sequence_nbr, $data);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? $e->getResponse()->getBody()->getContents() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = $responseBody->getContents();
                if ($returnType !== 'string') {
                    $content = json_decode($content);
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        'object',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation orderRegistrantsSetRegistrantApprovalAsync
     *
     * Extended (Registration Orders) - Set order registrant Approval Status
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\RegistrationApprovalsModel $data (Include in the HTTP Body) An RegistrationApprovalsModel entry to to change the approval status of a registrant. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsSetRegistrantApprovalAsync($org_code, $registrant_sequence_nbr, $data)
    {
        return $this->orderRegistrantsSetRegistrantApprovalAsyncWithHttpInfo($org_code, $registrant_sequence_nbr, $data)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation orderRegistrantsSetRegistrantApprovalAsyncWithHttpInfo
     *
     * Extended (Registration Orders) - Set order registrant Approval Status
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\RegistrationApprovalsModel $data (Include in the HTTP Body) An RegistrationApprovalsModel entry to to change the approval status of a registrant. (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function orderRegistrantsSetRegistrantApprovalAsyncWithHttpInfo($org_code, $registrant_sequence_nbr, $data)
    {
        $returnType = 'object';
        $request = $this->orderRegistrantsSetRegistrantApprovalRequest($org_code, $registrant_sequence_nbr, $data);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = $responseBody->getContents();
                        if ($returnType !== 'string') {
                            $content = json_decode($content);
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'orderRegistrantsSetRegistrantApproval'
     *
     * @param  string $org_code The organization code of the order registrant. (required)
     * @param  int $registrant_sequence_nbr The code of the order registrant. (required)
     * @param  \FomF\Ungerboeck\Client\Model\RegistrationApprovalsModel $data (Include in the HTTP Body) An RegistrationApprovalsModel entry to to change the approval status of a registrant. (required)
     *
     * @throws \InvalidArgumentException
     * @throws \GuzzleHttp\Exception\GuzzleException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function orderRegistrantsSetRegistrantApprovalRequest($org_code, $registrant_sequence_nbr, $data)
    {
        // verify the required parameter 'org_code' is set
        if ($org_code === null || (is_array($org_code) && count($org_code) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $org_code when calling orderRegistrantsSetRegistrantApproval'
            );
        }
        // verify the required parameter 'registrant_sequence_nbr' is set
        if ($registrant_sequence_nbr === null || (is_array($registrant_sequence_nbr) && count($registrant_sequence_nbr) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $registrant_sequence_nbr when calling orderRegistrantsSetRegistrantApproval'
            );
        }
        // verify the required parameter 'data' is set
        if ($data === null || (is_array($data) && count($data) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $data when calling orderRegistrantsSetRegistrantApproval'
            );
        }

        $resourcePath = '/api/v1/OrderRegistrants/{OrgCode}/{RegistrantSequenceNbr}/SetRegistrantApproval';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;


        // path params
        if ($org_code !== null) {
            $resourcePath = str_replace(
                '{' . 'OrgCode' . '}',
                ObjectSerializer::toPathValue($org_code),
                $resourcePath
            );
        }
        // path params
        if ($registrant_sequence_nbr !== null) {
            $resourcePath = str_replace(
                '{' . 'RegistrantSequenceNbr' . '}',
                ObjectSerializer::toPathValue($registrant_sequence_nbr),
                $resourcePath
            );
        }

        // body params
        $_tempBody = null;
        if (isset($data)) {
            $_tempBody = $data;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json', 'text/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json', 'text/json'],
                ['application/json', 'text/json', 'application/x-www-form-urlencoded']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            $httpBody = $_tempBody;
            // \stdClass has no __toString(), so we should encode it manually
            if ($httpBody instanceof \stdClass && $headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($httpBody);
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

   
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('Token');
        if ($apiKey !== null) {
            $headers['Token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);


        return new Request(
            'PUT',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
