<?php
/**
 * ContractsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FomF\Ungerboeck\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ungerboeck API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.1-SNAPSHOT
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FomF\Ungerboeck\Client;

/**
 * ContractsModelTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     FomF\Ungerboeck\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ContractsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ContractsModel"
     */
    public function testContractsModel()
    {
    }

    /**
     * Test attribute "organization"
     */
    public function testPropertyOrganization()
    {
    }

    /**
     * Test attribute "sequence"
     */
    public function testPropertySequence()
    {
    }

    /**
     * Test attribute "contract_id"
     */
    public function testPropertyContractId()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "written_date"
     */
    public function testPropertyWrittenDate()
    {
    }

    /**
     * Test attribute "due_date"
     */
    public function testPropertyDueDate()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "mailed_date"
     */
    public function testPropertyMailedDate()
    {
    }

    /**
     * Test attribute "signed_date"
     */
    public function testPropertySignedDate()
    {
    }

    /**
     * Test attribute "event"
     */
    public function testPropertyEvent()
    {
    }

    /**
     * Test attribute "account"
     */
    public function testPropertyAccount()
    {
    }

    /**
     * Test attribute "entered_on"
     */
    public function testPropertyEnteredOn()
    {
    }

    /**
     * Test attribute "entered_by"
     */
    public function testPropertyEnteredBy()
    {
    }

    /**
     * Test attribute "changed_on"
     */
    public function testPropertyChangedOn()
    {
    }

    /**
     * Test attribute "changed_by"
     */
    public function testPropertyChangedBy()
    {
    }

    /**
     * Test attribute "addendum"
     */
    public function testPropertyAddendum()
    {
    }

    /**
     * Test attribute "contract_rep"
     */
    public function testPropertyContractRep()
    {
    }

    /**
     * Test attribute "total"
     */
    public function testPropertyTotal()
    {
    }

    /**
     * Test attribute "decision_date"
     */
    public function testPropertyDecisionDate()
    {
    }

    /**
     * Test attribute "reference1"
     */
    public function testPropertyReference1()
    {
    }

    /**
     * Test attribute "reference2"
     */
    public function testPropertyReference2()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "revision_number"
     */
    public function testPropertyRevisionNumber()
    {
    }

    /**
     * Test attribute "contact"
     */
    public function testPropertyContact()
    {
    }

    /**
     * Test attribute "revision_status"
     */
    public function testPropertyRevisionStatus()
    {
    }

    /**
     * Test attribute "revision_date"
     */
    public function testPropertyRevisionDate()
    {
    }

    /**
     * Test attribute "revised_by"
     */
    public function testPropertyRevisedBy()
    {
    }

    /**
     * Test attribute "payment_plan"
     */
    public function testPropertyPaymentPlan()
    {
    }

    /**
     * Test attribute "high_status"
     */
    public function testPropertyHighStatus()
    {
    }

    /**
     * Test attribute "cancelled_on"
     */
    public function testPropertyCancelledOn()
    {
    }

    /**
     * Test attribute "cancellation_user_id"
     */
    public function testPropertyCancellationUserId()
    {
    }

    /**
     * Test attribute "cancellation_reason"
     */
    public function testPropertyCancellationReason()
    {
    }

    /**
     * Test attribute "locked"
     */
    public function testPropertyLocked()
    {
    }
}
