<?php
/**
 * ExpenseReportApprovalsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FomF\Ungerboeck\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ungerboeck API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FomF\Ungerboeck\Client;

/**
 * ExpenseReportApprovalsModelTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     FomF\Ungerboeck\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ExpenseReportApprovalsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ExpenseReportApprovalsModel"
     */
    public function testExpenseReportApprovalsModel()
    {
    }

    /**
     * Test attribute "log_sequence"
     */
    public function testPropertyLogSequence()
    {
    }

    /**
     * Test attribute "expense_report_id"
     */
    public function testPropertyExpenseReportId()
    {
    }

    /**
     * Test attribute "organization_code"
     */
    public function testPropertyOrganizationCode()
    {
    }

    /**
     * Test attribute "action"
     */
    public function testPropertyAction()
    {
    }

    /**
     * Test attribute "note"
     */
    public function testPropertyNote()
    {
    }

    /**
     * Test attribute "entered_by"
     */
    public function testPropertyEnteredBy()
    {
    }

    /**
     * Test attribute "entered_on"
     */
    public function testPropertyEnteredOn()
    {
    }
}
