<?php
/**
 * PriceListItemsModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FomF\Ungerboeck\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ungerboeck API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FomF\Ungerboeck\Client;

/**
 * PriceListItemsModelTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     FomF\Ungerboeck\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class PriceListItemsModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "PriceListItemsModel"
     */
    public function testPriceListItemsModel()
    {
    }

    /**
     * Test attribute "organization_code"
     */
    public function testPropertyOrganizationCode()
    {
    }

    /**
     * Test attribute "price_list"
     */
    public function testPropertyPriceList()
    {
    }

    /**
     * Test attribute "sequence"
     */
    public function testPropertySequence()
    {
    }

    /**
     * Test attribute "form"
     */
    public function testPropertyForm()
    {
    }

    /**
     * Test attribute "form_sequence"
     */
    public function testPropertyFormSequence()
    {
    }

    /**
     * Test attribute "type"
     */
    public function testPropertyType()
    {
    }

    /**
     * Test attribute "code"
     */
    public function testPropertyCode()
    {
    }

    /**
     * Test attribute "unitof_measure"
     */
    public function testPropertyUnitofMeasure()
    {
    }

    /**
     * Test attribute "standard_price"
     */
    public function testPropertyStandardPrice()
    {
    }

    /**
     * Test attribute "advance_price"
     */
    public function testPropertyAdvancePrice()
    {
    }

    /**
     * Test attribute "late_price"
     */
    public function testPropertyLatePrice()
    {
    }

    /**
     * Test attribute "standard_cost"
     */
    public function testPropertyStandardCost()
    {
    }

    /**
     * Test attribute "advance_cost"
     */
    public function testPropertyAdvanceCost()
    {
    }

    /**
     * Test attribute "late_cost"
     */
    public function testPropertyLateCost()
    {
    }

    /**
     * Test attribute "per_units"
     */
    public function testPropertyPerUnits()
    {
    }

    /**
     * Test attribute "unitof_time"
     */
    public function testPropertyUnitofTime()
    {
    }

    /**
     * Test attribute "minimum_charge"
     */
    public function testPropertyMinimumCharge()
    {
    }

    /**
     * Test attribute "maximum_charge"
     */
    public function testPropertyMaximumCharge()
    {
    }

    /**
     * Test attribute "description"
     */
    public function testPropertyDescription()
    {
    }

    /**
     * Test attribute "tax_rate_date"
     */
    public function testPropertyTaxRateDate()
    {
    }

    /**
     * Test attribute "entered_by"
     */
    public function testPropertyEnteredBy()
    {
    }

    /**
     * Test attribute "changed_by"
     */
    public function testPropertyChangedBy()
    {
    }

    /**
     * Test attribute "default"
     */
    public function testPropertyDefault()
    {
    }

    /**
     * Test attribute "show_delivery_dateand_time_show_start_date"
     */
    public function testPropertyShowDeliveryDateandTimeShowStartDate()
    {
    }

    /**
     * Test attribute "show_pickup_dateand_time_show_end_date"
     */
    public function testPropertyShowPickupDateandTimeShowEndDate()
    {
    }

    /**
     * Test attribute "require_note"
     */
    public function testPropertyRequireNote()
    {
    }

    /**
     * Test attribute "note_class"
     */
    public function testPropertyNoteClass()
    {
    }

    /**
     * Test attribute "minimum_quantity"
     */
    public function testPropertyMinimumQuantity()
    {
    }

    /**
     * Test attribute "maximum_quantity"
     */
    public function testPropertyMaximumQuantity()
    {
    }

    /**
     * Test attribute "additional_info_note_class"
     */
    public function testPropertyAdditionalInfoNoteClass()
    {
    }

    /**
     * Test attribute "pricing_tier1_through_quantity"
     */
    public function testPropertyPricingTier1ThroughQuantity()
    {
    }

    /**
     * Test attribute "pricing_tier2_through_quantity"
     */
    public function testPropertyPricingTier2ThroughQuantity()
    {
    }

    /**
     * Test attribute "pricing_tier3_through_quantity"
     */
    public function testPropertyPricingTier3ThroughQuantity()
    {
    }

    /**
     * Test attribute "pricing_tier4_through_quantity"
     */
    public function testPropertyPricingTier4ThroughQuantity()
    {
    }

    /**
     * Test attribute "pricing_tier1_type"
     */
    public function testPropertyPricingTier1Type()
    {
    }

    /**
     * Test attribute "pricing_tier2_type"
     */
    public function testPropertyPricingTier2Type()
    {
    }

    /**
     * Test attribute "pricing_tier3_type"
     */
    public function testPropertyPricingTier3Type()
    {
    }

    /**
     * Test attribute "pricing_tier4_type"
     */
    public function testPropertyPricingTier4Type()
    {
    }

    /**
     * Test attribute "price_method"
     */
    public function testPropertyPriceMethod()
    {
    }

    /**
     * Test attribute "price_base"
     */
    public function testPropertyPriceBase()
    {
    }

    /**
     * Test attribute "standard_price_percentage_markup"
     */
    public function testPropertyStandardPricePercentageMarkup()
    {
    }

    /**
     * Test attribute "advance_price_percentage_markup"
     */
    public function testPropertyAdvancePricePercentageMarkup()
    {
    }

    /**
     * Test attribute "base_price"
     */
    public function testPropertyBasePrice()
    {
    }

    /**
     * Test attribute "show_start_date"
     */
    public function testPropertyShowStartDate()
    {
    }

    /**
     * Test attribute "show_start_time"
     */
    public function testPropertyShowStartTime()
    {
    }

    /**
     * Test attribute "show_end_date"
     */
    public function testPropertyShowEndDate()
    {
    }

    /**
     * Test attribute "show_end_time"
     */
    public function testPropertyShowEndTime()
    {
    }

    /**
     * Test attribute "show_rate"
     */
    public function testPropertyShowRate()
    {
    }

    /**
     * Test attribute "show_units"
     */
    public function testPropertyShowUnits()
    {
    }

    /**
     * Test attribute "daily"
     */
    public function testPropertyDaily()
    {
    }

    /**
     * Test attribute "late_price_percentage_markup"
     */
    public function testPropertyLatePricePercentageMarkup()
    {
    }

    /**
     * Test attribute "pricing_tier5_through_quantity"
     */
    public function testPropertyPricingTier5ThroughQuantity()
    {
    }

    /**
     * Test attribute "pricing_tier5_type"
     */
    public function testPropertyPricingTier5Type()
    {
    }

    /**
     * Test attribute "use_tiered_pricing"
     */
    public function testPropertyUseTieredPricing()
    {
    }

    /**
     * Test attribute "tier5_base_price"
     */
    public function testPropertyTier5BasePrice()
    {
    }

    /**
     * Test attribute "not_used"
     */
    public function testPropertyNotUsed()
    {
    }

    /**
     * Test attribute "revenue_distribution"
     */
    public function testPropertyRevenueDistribution()
    {
    }

    /**
     * Test attribute "tax_inclusive"
     */
    public function testPropertyTaxInclusive()
    {
    }

    /**
     * Test attribute "header_only"
     */
    public function testPropertyHeaderOnly()
    {
    }

    /**
     * Test attribute "tier1_advance_price"
     */
    public function testPropertyTier1AdvancePrice()
    {
    }

    /**
     * Test attribute "tier2_advance_price"
     */
    public function testPropertyTier2AdvancePrice()
    {
    }

    /**
     * Test attribute "tier3_advance_price"
     */
    public function testPropertyTier3AdvancePrice()
    {
    }

    /**
     * Test attribute "tier4_advance_price"
     */
    public function testPropertyTier4AdvancePrice()
    {
    }

    /**
     * Test attribute "tier5_advance_price"
     */
    public function testPropertyTier5AdvancePrice()
    {
    }

    /**
     * Test attribute "tier1_standard_price"
     */
    public function testPropertyTier1StandardPrice()
    {
    }

    /**
     * Test attribute "tier2_standard_price"
     */
    public function testPropertyTier2StandardPrice()
    {
    }

    /**
     * Test attribute "tier3_standard_price"
     */
    public function testPropertyTier3StandardPrice()
    {
    }

    /**
     * Test attribute "tier4_standard_price"
     */
    public function testPropertyTier4StandardPrice()
    {
    }

    /**
     * Test attribute "tier5_standard_price"
     */
    public function testPropertyTier5StandardPrice()
    {
    }

    /**
     * Test attribute "tier1_late_price"
     */
    public function testPropertyTier1LatePrice()
    {
    }

    /**
     * Test attribute "tier2_late_price"
     */
    public function testPropertyTier2LatePrice()
    {
    }

    /**
     * Test attribute "tier3_late_price"
     */
    public function testPropertyTier3LatePrice()
    {
    }

    /**
     * Test attribute "tier4_late_price"
     */
    public function testPropertyTier4LatePrice()
    {
    }

    /**
     * Test attribute "tier5_late_price"
     */
    public function testPropertyTier5LatePrice()
    {
    }

    /**
     * Test attribute "member_item_type"
     */
    public function testPropertyMemberItemType()
    {
    }

    /**
     * Test attribute "shippable"
     */
    public function testPropertyShippable()
    {
    }

    /**
     * Test attribute "chargeable"
     */
    public function testPropertyChargeable()
    {
    }

    /**
     * Test attribute "active"
     */
    public function testPropertyActive()
    {
    }

    /**
     * Test attribute "item_supplier"
     */
    public function testPropertyItemSupplier()
    {
    }

    /**
     * Test attribute "round_time"
     */
    public function testPropertyRoundTime()
    {
    }

    /**
     * Test attribute "item_reference"
     */
    public function testPropertyItemReference()
    {
    }

    /**
     * Test attribute "pricing_scheme"
     */
    public function testPropertyPricingScheme()
    {
    }

    /**
     * Test attribute "cycle"
     */
    public function testPropertyCycle()
    {
    }

    /**
     * Test attribute "setup_price_list_detail_seq_nbr"
     */
    public function testPropertySetupPriceListDetailSeqNbr()
    {
    }

    /**
     * Test attribute "show_extended_charge"
     */
    public function testPropertyShowExtendedCharge()
    {
    }

    /**
     * Test attribute "use_tiered_costs"
     */
    public function testPropertyUseTieredCosts()
    {
    }

    /**
     * Test attribute "costing_scheme"
     */
    public function testPropertyCostingScheme()
    {
    }

    /**
     * Test attribute "cost_base"
     */
    public function testPropertyCostBase()
    {
    }

    /**
     * Test attribute "cost_method"
     */
    public function testPropertyCostMethod()
    {
    }

    /**
     * Test attribute "advance_cost_percentage_markup"
     */
    public function testPropertyAdvanceCostPercentageMarkup()
    {
    }

    /**
     * Test attribute "standard_cost_percentage_markup"
     */
    public function testPropertyStandardCostPercentageMarkup()
    {
    }

    /**
     * Test attribute "late_cost_percentage_markup"
     */
    public function testPropertyLateCostPercentageMarkup()
    {
    }

    /**
     * Test attribute "cost_tier1_through_quantity"
     */
    public function testPropertyCostTier1ThroughQuantity()
    {
    }

    /**
     * Test attribute "cost_tier2_through_quantity"
     */
    public function testPropertyCostTier2ThroughQuantity()
    {
    }

    /**
     * Test attribute "cost_tier3_through_quantity"
     */
    public function testPropertyCostTier3ThroughQuantity()
    {
    }

    /**
     * Test attribute "cost_tier4_through_quantity"
     */
    public function testPropertyCostTier4ThroughQuantity()
    {
    }

    /**
     * Test attribute "cost_tier5_through_quantity"
     */
    public function testPropertyCostTier5ThroughQuantity()
    {
    }

    /**
     * Test attribute "cost_tier1_type"
     */
    public function testPropertyCostTier1Type()
    {
    }

    /**
     * Test attribute "cost_tier2_type"
     */
    public function testPropertyCostTier2Type()
    {
    }

    /**
     * Test attribute "cost_tier3_type"
     */
    public function testPropertyCostTier3Type()
    {
    }

    /**
     * Test attribute "cost_tier4_type"
     */
    public function testPropertyCostTier4Type()
    {
    }

    /**
     * Test attribute "cost_tier5_type"
     */
    public function testPropertyCostTier5Type()
    {
    }

    /**
     * Test attribute "tier1_advance_cost"
     */
    public function testPropertyTier1AdvanceCost()
    {
    }

    /**
     * Test attribute "tier2_advance_cost"
     */
    public function testPropertyTier2AdvanceCost()
    {
    }

    /**
     * Test attribute "tier3_advance_cost"
     */
    public function testPropertyTier3AdvanceCost()
    {
    }

    /**
     * Test attribute "tier4_advance_cost"
     */
    public function testPropertyTier4AdvanceCost()
    {
    }

    /**
     * Test attribute "tier5_advance_cost"
     */
    public function testPropertyTier5AdvanceCost()
    {
    }

    /**
     * Test attribute "tier1_standard_cost"
     */
    public function testPropertyTier1StandardCost()
    {
    }

    /**
     * Test attribute "tier2_standard_cost"
     */
    public function testPropertyTier2StandardCost()
    {
    }

    /**
     * Test attribute "tier3_standard_cost"
     */
    public function testPropertyTier3StandardCost()
    {
    }

    /**
     * Test attribute "tier4_standard_cost"
     */
    public function testPropertyTier4StandardCost()
    {
    }

    /**
     * Test attribute "tier5_standard_cost"
     */
    public function testPropertyTier5StandardCost()
    {
    }

    /**
     * Test attribute "tier1_late_cost"
     */
    public function testPropertyTier1LateCost()
    {
    }

    /**
     * Test attribute "tier2_late_cost"
     */
    public function testPropertyTier2LateCost()
    {
    }

    /**
     * Test attribute "tier3_late_cost"
     */
    public function testPropertyTier3LateCost()
    {
    }

    /**
     * Test attribute "tier4_late_cost"
     */
    public function testPropertyTier4LateCost()
    {
    }

    /**
     * Test attribute "tier5_late_cost"
     */
    public function testPropertyTier5LateCost()
    {
    }

    /**
     * Test attribute "base_cost"
     */
    public function testPropertyBaseCost()
    {
    }

    /**
     * Test attribute "alternate_description1"
     */
    public function testPropertyAlternateDescription1()
    {
    }

    /**
     * Test attribute "alternate_description2"
     */
    public function testPropertyAlternateDescription2()
    {
    }

    /**
     * Test attribute "alternate_description3"
     */
    public function testPropertyAlternateDescription3()
    {
    }

    /**
     * Test attribute "alternate_description4"
     */
    public function testPropertyAlternateDescription4()
    {
    }

    /**
     * Test attribute "alternate_description5"
     */
    public function testPropertyAlternateDescription5()
    {
    }

    /**
     * Test attribute "default_for"
     */
    public function testPropertyDefaultFor()
    {
    }

    /**
     * Test attribute "include_time_when_displaying_rate"
     */
    public function testPropertyIncludeTimeWhenDisplayingRate()
    {
    }

    /**
     * Test attribute "allow_file_upload"
     */
    public function testPropertyAllowFileUpload()
    {
    }

    /**
     * Test attribute "file_upload_required"
     */
    public function testPropertyFileUploadRequired()
    {
    }

    /**
     * Test attribute "document_category"
     */
    public function testPropertyDocumentCategory()
    {
    }

    /**
     * Test attribute "maximum_numberof_files"
     */
    public function testPropertyMaximumNumberofFiles()
    {
    }

    /**
     * Test attribute "document_sensitivity"
     */
    public function testPropertyDocumentSensitivity()
    {
    }

    /**
     * Test attribute "use_datesand_timesfor_item_selection"
     */
    public function testPropertyUseDatesandTimesforItemSelection()
    {
    }

    /**
     * Test attribute "third_party_billed"
     */
    public function testPropertyThirdPartyBilled()
    {
    }

    /**
     * Test attribute "file_upload_instructions"
     */
    public function testPropertyFileUploadInstructions()
    {
    }

    /**
     * Test attribute "alternate_file_upload_instructions1"
     */
    public function testPropertyAlternateFileUploadInstructions1()
    {
    }

    /**
     * Test attribute "alternate_file_upload_instructions2"
     */
    public function testPropertyAlternateFileUploadInstructions2()
    {
    }

    /**
     * Test attribute "alternate_file_upload_instructions3"
     */
    public function testPropertyAlternateFileUploadInstructions3()
    {
    }

    /**
     * Test attribute "alternate_file_upload_instructions4"
     */
    public function testPropertyAlternateFileUploadInstructions4()
    {
    }

    /**
     * Test attribute "alternate_file_upload_instructions5"
     */
    public function testPropertyAlternateFileUploadInstructions5()
    {
    }

    /**
     * Test attribute "default_upload_description"
     */
    public function testPropertyDefaultUploadDescription()
    {
    }
}
