<?php
/**
 * UsersModelTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  FomF\Ungerboeck\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Ungerboeck API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace FomF\Ungerboeck\Client;

/**
 * UsersModelTest Class Doc Comment
 *
 * @category    Class
 * @description 
 * @package     FomF\Ungerboeck\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class UsersModelTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "UsersModel"
     */
    public function testUsersModel()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "display_name"
     */
    public function testPropertyDisplayName()
    {
    }

    /**
     * Test attribute "organization"
     */
    public function testPropertyOrganization()
    {
    }

    /**
     * Test attribute "initial_menu"
     */
    public function testPropertyInitialMenu()
    {
    }

    /**
     * Test attribute "group"
     */
    public function testPropertyGroup()
    {
    }

    /**
     * Test attribute "entered_by_code"
     */
    public function testPropertyEnteredByCode()
    {
    }

    /**
     * Test attribute "changed_by_code"
     */
    public function testPropertyChangedByCode()
    {
    }

    /**
     * Test attribute "initials"
     */
    public function testPropertyInitials()
    {
    }

    /**
     * Test attribute "hold"
     */
    public function testPropertyHold()
    {
    }

    /**
     * Test attribute "working_directory"
     */
    public function testPropertyWorkingDirectory()
    {
    }

    /**
     * Test attribute "printer"
     */
    public function testPropertyPrinter()
    {
    }

    /**
     * Test attribute "report_cache_quantity"
     */
    public function testPropertyReportCacheQuantity()
    {
    }

    /**
     * Test attribute "retire"
     */
    public function testPropertyRetire()
    {
    }

    /**
     * Test attribute "login_id"
     */
    public function testPropertyLoginId()
    {
    }

    /**
     * Test attribute "theme"
     */
    public function testPropertyTheme()
    {
    }

    /**
     * Test attribute "reply_to_email"
     */
    public function testPropertyReplyToEmail()
    {
    }

    /**
     * Test attribute "dictionary"
     */
    public function testPropertyDictionary()
    {
    }

    /**
     * Test attribute "spell_check"
     */
    public function testPropertySpellCheck()
    {
    }

    /**
     * Test attribute "email_notification"
     */
    public function testPropertyEmailNotification()
    {
    }

    /**
     * Test attribute "custom_report_dictionary"
     */
    public function testPropertyCustomReportDictionary()
    {
    }

    /**
     * Test attribute "email_send_process"
     */
    public function testPropertyEmailSendProcess()
    {
    }

    /**
     * Test attribute "remote_access"
     */
    public function testPropertyRemoteAccess()
    {
    }

    /**
     * Test attribute "activation_status"
     */
    public function testPropertyActivationStatus()
    {
    }

    /**
     * Test attribute "email"
     */
    public function testPropertyEmail()
    {
    }

    /**
     * Test attribute "password_established"
     */
    public function testPropertyPasswordEstablished()
    {
    }

    /**
     * Test attribute "locked"
     */
    public function testPropertyLocked()
    {
    }

    /**
     * Test attribute "locked_on"
     */
    public function testPropertyLockedOn()
    {
    }

    /**
     * Test attribute "invalid_attempts"
     */
    public function testPropertyInvalidAttempts()
    {
    }

    /**
     * Test attribute "first_invalid_attempt"
     */
    public function testPropertyFirstInvalidAttempt()
    {
    }

    /**
     * Test attribute "dashboard"
     */
    public function testPropertyDashboard()
    {
    }

    /**
     * Test attribute "mobile_access"
     */
    public function testPropertyMobileAccess()
    {
    }

    /**
     * Test attribute "mobile_theme"
     */
    public function testPropertyMobileTheme()
    {
    }

    /**
     * Test attribute "access_level"
     */
    public function testPropertyAccessLevel()
    {
    }

    /**
     * Test attribute "startup_favorite"
     */
    public function testPropertyStartupFavorite()
    {
    }

    /**
     * Test attribute "default_zoom_amount"
     */
    public function testPropertyDefaultZoomAmount()
    {
    }

    /**
     * Test attribute "auth_configuration"
     */
    public function testPropertyAuthConfiguration()
    {
    }

    /**
     * Test attribute "always_use_default_view"
     */
    public function testPropertyAlwaysUseDefaultView()
    {
    }

    /**
     * Test attribute "locale"
     */
    public function testPropertyLocale()
    {
    }

    /**
     * Test attribute "color_scheme_mode"
     */
    public function testPropertyColorSchemeMode()
    {
    }

    /**
     * Test attribute "entered_on"
     */
    public function testPropertyEnteredOn()
    {
    }

    /**
     * Test attribute "changed_on"
     */
    public function testPropertyChangedOn()
    {
    }

    /**
     * Test attribute "user_type"
     */
    public function testPropertyUserType()
    {
    }

    /**
     * Test attribute "exhibition_user_type"
     */
    public function testPropertyExhibitionUserType()
    {
    }
}
